# Generated by Django 4.1.5 on 2023-01-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('house_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.address')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contact')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.product')),
                ('supplier', models.ManyToManyField(to='e_chain.retail')),
            ],
            options={
                'verbose_name': 'Крупная розничная сеть',
                'verbose_name_plural': 'Крупные розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contact')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.product')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contact')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.product')),
                ('supplier', models.ManyToManyField(to='e_chain.entrepreneur')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contact')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.product')),
                ('supplier', models.ManyToManyField(to='e_chain.distributor')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff', models.IntegerField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contact')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.product')),
                ('supplier', models.ManyToManyField(to='e_chain.dealership')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
    ]
