# Generated by Django 4.1.5 on 2023-01-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('staff', models.JSONField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('staff', models.JSONField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('staff', models.JSONField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.dealership')),
            ],
            options={
                'verbose_name': 'Крупная розничная сеть',
                'verbose_name_plural': 'Крупные розничные сети',
            },
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('staff', models.JSONField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.retail')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('staff', models.JSONField(blank=True, null=True)),
                ('debt', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.factory')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
            },
        ),
        migrations.AddField(
            model_name='dealership',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.distributor'),
        ),
    ]
