# Generated by Django 4.1.5 on 2023-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='retail',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='retail',
            name='supplier',
        ),
        migrations.AddField(
            model_name='dealership',
            name='supplier',
            field=models.ManyToManyField(related_name='поставщик', to='e_chain.dealership'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='supplier',
            field=models.ManyToManyField(related_name='поставщик', to='e_chain.distributor'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='supplier',
            field=models.ManyToManyField(related_name='поставщик', to='e_chain.entrepreneur'),
        ),
        migrations.AddField(
            model_name='factory',
            name='supplier',
            field=models.ManyToManyField(related_name='поставщик', to='e_chain.factory'),
        ),
        migrations.AddField(
            model_name='retail',
            name='supplier',
            field=models.ManyToManyField(related_name='поставщик', to='e_chain.retail'),
        ),
    ]
