# Generated by Django 4.1.5 on 2023-01-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='supplier',
        ),
        migrations.AddField(
            model_name='dealership',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_chain.dealership'),
        ),
    ]
