# Generated by Django 4.1.5 on 2023-01-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('house_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_chain.address')),
            ],
        ),
        migrations.AlterField(
            model_name='dealership',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contacts'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.products'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.staff'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contacts'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.products'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.staff'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contacts'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.products'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.staff'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contacts'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.products'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.staff'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.contacts'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.products'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.staff'),
        ),
    ]
