# Generated by Django 4.1.5 on 2023-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0002_remove_dealership_supplier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='chain_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='chain_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='chain_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='chain_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='retail',
            name='chain_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='dealership',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='retail',
            name='supplier',
        ),
        migrations.AddField(
            model_name='dealership',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='factory',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='retail',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
    ]
