# Generated by Django 4.1.5 on 2023-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0003_factory_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='factory',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.RemoveField(
            model_name='retail',
            name='supplier',
        ),
        migrations.AddField(
            model_name='distributor',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='retail',
            name='supplier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилерский центр'), (4, 'Крупная розничная сеть'), (5, 'Индивидуальный предприниматель')], null=True, verbose_name='Поставщик'),
        ),
    ]
