# Generated by Django 4.1.5 on 2023-01-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0004_alter_dealership_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.dealership'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.distributor'),
        ),
        migrations.AddField(
            model_name='entrepreneur',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.entrepreneur'),
        ),
        migrations.AddField(
            model_name='factory',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.factory'),
        ),
        migrations.AddField(
            model_name='retail',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_chain.retail'),
        ),
    ]
