# Generated by Django 4.1.5 on 2023-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_chain', '0005_alter_dealership_supplier_alter_distributor_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='entrepreneur',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='retail',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
